# Generated by Django 6.0.6 on 2026-07-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GameTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_themes', to='game_window.game')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('game_theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_theme', to='game_window.gametheme')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('is_open', models.BooleanField(default=False)),
                ('there_photo', models.BooleanField(default=False)),
                ('there_music', models.BooleanField(default=False)),
                ('photo_path', models.CharField(max_length=128)),
                ('music_path', models.CharField(max_length=128)),
                ('question_theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game_window.questiontheme')),
            ],
        ),
    ]
