# Generated by Django 6.0.6 on 2026-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_window', '0002_game_active_game_created_at_game_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(default=None, upload_to='music/'),
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.DurationField(default=None, help_text='Длительность (HH:MM:SS)'),
        ),
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(default=None, upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='music_path',
            field=models.CharField(default='music/', max_length=128),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo_path',
            field=models.CharField(default='picture/', max_length=128),
        ),
    ]
