# Generated by Django 6.0.6 on 2026-07-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_window', '0003_question_audio_file_question_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
