# Generated by Django 6.0.6 on 2026-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('surname', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('link_vk', models.URLField(max_length=500)),
                ('link_tg', models.URLField(max_length=500)),
                ('link_mail', models.URLField(max_length=500)),
                ('photo', models.ImageField(upload_to='avatars/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
