# Generated by Django 6.0.6 on 2026-07-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='position_eng',
        ),
        migrations.AddField(
            model_name='employee',
            name='position_description',
            field=models.CharField(default=str, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position_ru',
            field=models.CharField(default=str, max_length=128),
            preserve_default=False,
        ),
    ]
